from __future__ import annotations

from sqlalchemy import select

from app.config import settings
from app.models import AppSetting, Source, User
from app.security import hash_password


DEFAULT_SOURCES = [
    {
        "name": "中国政府网政策",
        "domain": "gov.cn",
        "type": "policy",
        "priority": 95,
        "tags": ["policy", "cn"],
        "include_rules": ["政策", "塑料", "材料", "制造"],
        "exclude_rules": [],
        "must_include_any": ["材料", "塑料", "高分子", "回收", "制造", "绿色"],
        "must_exclude_any": ["体育", "房产", "股票", "中签", "招聘"],
        "soft_signals": ["政策", "标准", "制造", "循环经济"],
        "source_tier": "government",
        "rss_or_listing_url": None,
        "crawl_mode": "search",
        "use_direct_source": False,
        "allow_images": False,
        "language": "zh",
        "country": "CN",
        "enabled": True,
    },
    {
        "name": "中国工业和信息化部",
        "domain": "miit.gov.cn",
        "type": "policy",
        "priority": 90,
        "tags": ["policy", "industry"],
        "include_rules": ["材料", "制造", "绿色", "回收"],
        "exclude_rules": [],
        "must_include_any": ["材料", "制造", "塑料", "高分子", "回收"],
        "must_exclude_any": ["体育", "房产", "股票", "招聘"],
        "soft_signals": ["工信", "制造业", "绿色低碳"],
        "source_tier": "government",
        "rss_or_listing_url": "https://www.miit.gov.cn/xwfb/gxdt/index.html",
        "crawl_mode": "listing",
        "use_direct_source": True,
        "allow_images": False,
        "language": "zh",
        "country": "CN",
        "enabled": True,
    },
    {
        "name": "国家标准全文公开系统",
        "domain": "std.samr.gov.cn",
        "type": "policy",
        "priority": 87,
        "tags": ["policy", "standards", "cn"],
        "include_rules": ["塑料", "材料", "包装", "回收"],
        "exclude_rules": ["食品", "体育", "地产"],
        "must_include_any": ["塑料", "材料", "包装", "回收", "高分子", "标准"],
        "must_exclude_any": ["体育", "房产", "股票", "招聘"],
        "soft_signals": ["标准", "检测", "合规", "再生"],
        "source_tier": "standards",
        "rss_or_listing_url": None,
        "crawl_mode": "search",
        "use_direct_source": False,
        "allow_images": False,
        "language": "zh",
        "country": "CN",
        "enabled": True,
    },
    {
        "name": "国家市场监督管理总局标准",
        "domain": "samr.gov.cn",
        "type": "policy",
        "priority": 88,
        "tags": ["policy", "standards", "cn"],
        "include_rules": ["标准", "材料", "塑料"],
        "exclude_rules": [],
        "must_include_any": ["标准", "材料", "塑料", "回收", "包装"],
        "must_exclude_any": ["体育", "房产", "股票", "招聘"],
        "soft_signals": ["标准", "质量", "合规"],
        "source_tier": "standards",
        "rss_or_listing_url": None,
        "crawl_mode": "search",
        "use_direct_source": False,
        "allow_images": False,
        "language": "zh",
        "country": "CN",
        "enabled": True,
    },
    {
        "name": "国家发展改革委",
        "domain": "ndrc.gov.cn",
        "type": "policy",
        "priority": 84,
        "tags": ["policy", "recycling", "cn"],
        "include_rules": ["循环", "回收", "制造", "材料"],
        "exclude_rules": [],
        "must_include_any": ["循环", "回收", "制造", "材料", "绿色"],
        "must_exclude_any": ["体育", "房产", "股票", "招聘"],
        "soft_signals": ["循环经济", "绿色制造", "双碳"],
        "source_tier": "government",
        "rss_or_listing_url": None,
        "crawl_mode": "search",
        "use_direct_source": False,
        "allow_images": False,
        "language": "zh",
        "country": "CN",
        "enabled": True,
    },
    {
        "name": "生态环境部",
        "domain": "mee.gov.cn",
        "type": "policy",
        "priority": 82,
        "tags": ["policy", "environment", "cn"],
        "include_rules": ["塑料", "污染", "回收", "材料"],
        "exclude_rules": [],
        "must_include_any": ["塑料", "污染", "回收", "材料", "包装"],
        "must_exclude_any": ["体育", "房产", "股票", "招聘"],
        "soft_signals": ["塑料污染治理", "环保", "回收"],
        "source_tier": "government",
        "rss_or_listing_url": None,
        "crawl_mode": "search",
        "use_direct_source": False,
        "allow_images": False,
        "language": "zh",
        "country": "CN",
        "enabled": True,
    },
    {
        "name": "广东省工业和信息化厅",
        "domain": "gdii.gd.gov.cn",
        "type": "policy",
        "priority": 76,
        "tags": ["policy", "industry", "local"],
        "include_rules": ["新材料", "制造业", "绿色", "回收"],
        "exclude_rules": ["体育", "房产", "股票"],
        "must_include_any": ["新材料", "制造业", "塑料", "高分子", "绿色", "回收"],
        "must_exclude_any": ["体育", "房产", "股票", "招聘"],
        "soft_signals": ["技改", "产业链", "制造业", "绿色低碳"],
        "source_tier": "government",
        "rss_or_listing_url": None,
        "crawl_mode": "search",
        "use_direct_source": False,
        "allow_images": False,
        "language": "zh",
        "country": "CN",
        "enabled": True,
    },
    {
        "name": "北京市经济和信息化局",
        "domain": "jxj.beijing.gov.cn",
        "type": "policy",
        "priority": 74,
        "tags": ["policy", "industry", "local"],
        "include_rules": ["新材料", "制造", "绿色", "产业"],
        "exclude_rules": ["体育", "房产", "股票"],
        "must_include_any": ["新材料", "制造", "塑料", "高分子", "绿色", "产业"],
        "must_exclude_any": ["体育", "房产", "股票", "招聘"],
        "soft_signals": ["产业政策", "智能制造", "绿色制造"],
        "source_tier": "government",
        "rss_or_listing_url": None,
        "crawl_mode": "search",
        "use_direct_source": False,
        "allow_images": False,
        "language": "zh",
        "country": "CN",
        "enabled": True,
    },
    {
        "name": "江苏省工业和信息化厅",
        "domain": "gxt.jiangsu.gov.cn",
        "type": "policy",
        "priority": 74,
        "tags": ["policy", "industry", "local"],
        "include_rules": ["新材料", "制造", "工业", "回收"],
        "exclude_rules": ["体育", "房产", "股票"],
        "must_include_any": ["新材料", "制造", "塑料", "高分子", "工业", "回收"],
        "must_exclude_any": ["体育", "房产", "股票", "招聘"],
        "soft_signals": ["制造业", "智能化改造", "绿色工厂"],
        "source_tier": "government",
        "rss_or_listing_url": None,
        "crawl_mode": "search",
        "use_direct_source": False,
        "allow_images": False,
        "language": "zh",
        "country": "CN",
        "enabled": True,
    },
    {
        "name": "中塑在线",
        "domain": "plasticsnet.com.cn",
        "type": "industry",
        "priority": 86,
        "tags": ["industry", "plastics", "cn"],
        "include_rules": ["塑料", "高分子", "注塑", "挤出"],
        "exclude_rules": ["股市", "房产", "体育"],
        "must_include_any": ["塑料", "高分子", "注塑", "挤出", "改性", "回收"],
        "must_exclude_any": ["股票", "中签", "招聘", "体育", "房产"],
        "soft_signals": ["设备", "产能", "材料价格"],
        "source_tier": "top-industry-media",
        "rss_or_listing_url": None,
        "crawl_mode": "search",
        "use_direct_source": False,
        "allow_images": True,
        "language": "zh",
        "country": "CN",
        "enabled": True,
    },
    {
        "name": "雅式橡塑网",
        "domain": "adsalecprj.com",
        "type": "industry",
        "priority": 85,
        "tags": ["industry", "plastics", "equipment"],
        "include_rules": ["橡塑", "塑料", "注塑", "挤出", "包装"],
        "exclude_rules": ["股市", "体育"],
        "must_include_any": ["橡塑", "塑料", "注塑", "挤出", "回收", "包装"],
        "must_exclude_any": ["股票", "中签", "体育", "房产"],
        "soft_signals": ["设备", "展会", "企业动态"],
        "source_tier": "top-industry-media",
        "rss_or_listing_url": None,
        "crawl_mode": "search",
        "use_direct_source": False,
        "allow_images": True,
        "language": "zh",
        "country": "HK",
        "enabled": True,
    },
    {
        "name": "现代塑料",
        "domain": "xdplas.com",
        "type": "industry",
        "priority": 80,
        "tags": ["industry", "equipment", "cn"],
        "include_rules": ["塑料", "注塑", "挤出", "模具"],
        "exclude_rules": ["股市", "体育"],
        "must_include_any": ["塑料", "注塑", "挤出", "模具", "设备"],
        "must_exclude_any": ["股票", "中签", "体育", "房产"],
        "soft_signals": ["装备", "工艺", "制品"],
        "source_tier": "top-industry-media",
        "rss_or_listing_url": None,
        "crawl_mode": "search",
        "use_direct_source": False,
        "allow_images": True,
        "language": "zh",
        "country": "CN",
        "enabled": True,
    },
    {
        "name": "中国塑料机械网",
        "domain": "86pla.com",
        "type": "industry",
        "priority": 78,
        "tags": ["industry", "machinery", "cn"],
        "include_rules": ["塑机", "注塑机", "挤出机", "设备"],
        "exclude_rules": ["股市", "体育"],
        "must_include_any": ["塑机", "注塑机", "挤出机", "设备", "模具"],
        "must_exclude_any": ["股票", "中签", "体育", "房产"],
        "soft_signals": ["产线", "自动化", "装备"],
        "source_tier": "top-industry-media",
        "rss_or_listing_url": "https://www.86pla.com/news/",
        "crawl_mode": "listing",
        "use_direct_source": False,
        "allow_images": True,
        "language": "zh",
        "country": "CN",
        "enabled": True,
    },
    {
        "name": "塑料机械网行业资讯",
        "domain": "plas.hc360.com",
        "type": "industry",
        "priority": 72,
        "tags": ["industry", "machinery", "cn"],
        "include_rules": ["塑料", "设备", "注塑", "挤出"],
        "exclude_rules": ["股市", "体育"],
        "must_include_any": ["塑料", "设备", "注塑", "挤出", "材料"],
        "must_exclude_any": ["股票", "中签", "体育", "房产"],
        "soft_signals": ["供应链", "企业动态", "装备"],
        "source_tier": "top-industry-media",
        "rss_or_listing_url": None,
        "crawl_mode": "search",
        "use_direct_source": False,
        "allow_images": True,
        "language": "zh",
        "country": "CN",
        "enabled": True,
    },
    {
        "name": "DigiTimes 中文产业",
        "domain": "digitimes.com.tw",
        "type": "industry",
        "priority": 76,
        "tags": ["industry", "electronics", "materials"],
        "include_rules": ["材料", "塑料", "复合材料", "设备", "制造"],
        "exclude_rules": ["股市", "体育", "房产"],
        "must_include_any": ["材料", "塑料", "高分子", "复合材料", "设备", "制造"],
        "must_exclude_any": ["股票", "中签", "体育", "房产", "招聘"],
        "soft_signals": ["供应链", "扩产", "产线", "设备"],
        "source_tier": "top-industry-media",
        "rss_or_listing_url": None,
        "crawl_mode": "search",
        "use_direct_source": False,
        "allow_images": True,
        "language": "zh",
        "country": "TW",
        "enabled": True,
    },
    {
        "name": "3DPrint 产业观察",
        "domain": "3dprint.com",
        "type": "industry",
        "priority": 76,
        "tags": ["industry", "additive", "polymer"],
        "include_rules": ["additive manufacturing", "3d printing", "polymer", "resin"],
        "exclude_rules": ["stock", "sports", "celebrity"],
        "must_include_any": ["additive manufacturing", "3d printing", "post-processing", "polymer", "resin", "manufacturing"],
        "must_exclude_any": ["stock", "sports", "celebrity", "forecast period", "mortgage"],
        "soft_signals": ["automation", "production", "materials", "equipment"],
        "source_tier": "top-industry-media",
        "rss_or_listing_url": None,
        "crawl_mode": "search",
        "use_direct_source": False,
        "allow_images": True,
        "language": "en",
        "country": "US",
        "enabled": True,
    },
    {
        "name": "中国塑协",
        "domain": "cppia.com.cn",
        "type": "industry",
        "priority": 77,
        "tags": ["industry", "association", "plastics"],
        "include_rules": ["塑料", "改性", "再生", "降解"],
        "exclude_rules": ["体育", "房产", "股票"],
        "must_include_any": ["塑料", "改性", "再生", "降解", "包装", "回收"],
        "must_exclude_any": ["体育", "房产", "股票", "招聘"],
        "soft_signals": ["协会", "行业", "标准", "科技大会"],
        "source_tier": "top-industry-media",
        "rss_or_listing_url": None,
        "crawl_mode": "search",
        "use_direct_source": False,
        "allow_images": True,
        "language": "zh",
        "country": "CN",
        "enabled": True,
    },
    {
        "name": "中国塑机协会",
        "domain": "cpmia.org.cn",
        "type": "industry",
        "priority": 75,
        "tags": ["industry", "association", "machinery"],
        "include_rules": ["塑机", "注塑机", "挤出机", "设备"],
        "exclude_rules": ["体育", "房产", "股票"],
        "must_include_any": ["塑机", "注塑机", "挤出机", "设备", "吹塑", "自动化"],
        "must_exclude_any": ["体育", "房产", "股票", "招聘"],
        "soft_signals": ["协会", "装备", "行业", "企业排序"],
        "source_tier": "top-industry-media",
        "rss_or_listing_url": None,
        "crawl_mode": "search",
        "use_direct_source": False,
        "allow_images": True,
        "language": "zh",
        "country": "CN",
        "enabled": True,
    },
    {
        "name": "塑料再生与循环资讯",
        "domain": "replasinfo.com",
        "type": "industry",
        "priority": 74,
        "tags": ["industry", "recycling", "cn"],
        "include_rules": ["回收", "再生", "塑料", "循环"],
        "exclude_rules": ["体育", "房产", "股票"],
        "must_include_any": ["回收", "再生", "塑料", "循环", "包装", "再利用"],
        "must_exclude_any": ["体育", "房产", "股票", "招聘"],
        "soft_signals": ["rPET", "再生料", "闭环", "循环经济"],
        "source_tier": "top-industry-media",
        "rss_or_listing_url": None,
        "crawl_mode": "search",
        "use_direct_source": False,
        "allow_images": True,
        "language": "zh",
        "country": "CN",
        "enabled": True,
    },
    {
        "name": "Resource Media Recycling",
        "domain": "resourcemedia.eco",
        "type": "policy",
        "priority": 72,
        "tags": ["policy", "recycling", "global"],
        "include_rules": ["plastic", "recycling", "reprocessing", "packaging"],
        "exclude_rules": ["sports", "housing", "stock"],
        "must_include_any": ["plastic", "recycling", "reprocessing", "packaging", "policy", "waste"],
        "must_exclude_any": ["sports", "housing", "stock", "celebrity"],
        "soft_signals": ["compliance", "EPR", "waste", "circular economy"],
        "source_tier": "top-industry-media",
        "rss_or_listing_url": None,
        "crawl_mode": "search",
        "use_direct_source": False,
        "allow_images": True,
        "language": "en",
        "country": "GB",
        "enabled": True,
    },
    {
        "name": "Down To Earth Plastic Policy",
        "domain": "downtoearth.org.in",
        "type": "policy",
        "priority": 71,
        "tags": ["policy", "recycling", "global"],
        "include_rules": ["plastic", "waste", "EPR", "packaging"],
        "exclude_rules": ["sports", "housing", "stock"],
        "must_include_any": ["plastic", "waste", "EPR", "packaging", "recycling"],
        "must_exclude_any": ["sports", "housing", "stock", "celebrity"],
        "soft_signals": ["policy", "compliance", "environment", "packaging waste"],
        "source_tier": "top-industry-media",
        "rss_or_listing_url": None,
        "crawl_mode": "search",
        "use_direct_source": False,
        "allow_images": True,
        "language": "en",
        "country": "IN",
        "enabled": True,
    },
    {
        "name": "Packaging Gateway",
        "domain": "packaging-gateway.com",
        "type": "industry",
        "priority": 70,
        "tags": ["industry", "packaging", "equipment"],
        "include_rules": ["packaging", "equipment", "recycling", "materials"],
        "exclude_rules": ["sports", "housing", "stock"],
        "must_include_any": ["packaging", "equipment", "recycling", "materials", "machinery"],
        "must_exclude_any": ["sports", "housing", "stock", "forecast period"],
        "soft_signals": ["compliance", "machine", "processing", "manufacturing"],
        "source_tier": "top-industry-media",
        "rss_or_listing_url": None,
        "crawl_mode": "search",
        "use_direct_source": False,
        "allow_images": True,
        "language": "en",
        "country": "GB",
        "enabled": True,
    },
    {
        "name": "海天新闻中心",
        "domain": "newsroom.haitian.com",
        "type": "industry",
        "priority": 79,
        "tags": ["company", "equipment", "cn"],
        "include_rules": ["注塑机", "设备", "制造", "自动化"],
        "exclude_rules": ["体育", "房产", "股票"],
        "must_include_any": ["注塑机", "设备", "制造", "自动化", "高分子", "塑料"],
        "must_exclude_any": ["体育", "房产", "股票", "招聘"],
        "soft_signals": ["交付", "产线", "解决方案", "工厂"],
        "source_tier": "company-newsroom",
        "rss_or_listing_url": "https://newsroom.haitian.com/cn/news-cn/",
        "crawl_mode": "listing",
        "use_direct_source": False,
        "allow_images": True,
        "language": "zh",
        "country": "CN",
        "enabled": True,
    },
    {
        "name": "金发科技公司新闻",
        "domain": "kingfa.com.cn",
        "type": "industry",
        "priority": 78,
        "tags": ["company", "materials", "cn"],
        "include_rules": ["改性塑料", "生物降解", "再生塑料", "材料"],
        "exclude_rules": ["体育", "房产", "股票"],
        "must_include_any": ["改性塑料", "生物降解", "再生塑料", "材料", "高分子", "复合材料"],
        "must_exclude_any": ["体育", "房产", "股票", "招聘"],
        "soft_signals": ["项目", "投产", "合作", "绿色材料"],
        "source_tier": "company-newsroom",
        "rss_or_listing_url": "https://www.kingfa.com.cn/portal/list/index/id/5.html",
        "crawl_mode": "listing",
        "use_direct_source": True,
        "allow_images": True,
        "language": "zh",
        "country": "CN",
        "enabled": True,
    },
    # ── Verified RSS Sources (Phase 1) ──
    # English — Industry Media
    {
        "name": "Plastics News",
        "domain": "plasticsnews.com",
        "type": "rss",
        "priority": 90,
        "tags": ["industry", "en"],
        "include_rules": ["polymer", "plastics", "resin", "processing"],
        "exclude_rules": ["stock", "sports"],
        "must_include_any": ["polymer", "plastics", "resin", "processing", "recycling"],
        "must_exclude_any": ["stock", "sports", "celebrity"],
        "soft_signals": ["industry", "manufacturing", "market"],
        "source_tier": "B",
        "rss_or_listing_url": "https://www.plasticsnews.com/section/rss",
        "crawl_mode": "rss",
        "use_direct_source": True,
        "allow_images": True,
        "language": "en",
        "country": "US",
        "enabled": True,
    },
    {
        "name": "Plastics Technology",
        "domain": "ptonline.com",
        "type": "rss",
        "priority": 85,
        "tags": ["industry", "en"],
        "include_rules": ["polymer", "plastics", "processing", "equipment"],
        "exclude_rules": ["stock", "sports"],
        "must_include_any": ["polymer", "plastics", "processing", "equipment", "injection", "extrusion"],
        "must_exclude_any": ["stock", "sports", "celebrity"],
        "soft_signals": ["technology", "equipment", "manufacturing"],
        "source_tier": "B",
        "rss_or_listing_url": "https://www.ptonline.com/rss/blog",
        "crawl_mode": "rss",
        "use_direct_source": True,
        "allow_images": True,
        "language": "en",
        "country": "US",
        "enabled": False,  # 403 Forbidden
    },
    {
        "name": "CompositesWorld",
        "domain": "compositesworld.com",
        "type": "rss",
        "priority": 85,
        "tags": ["industry", "en"],
        "include_rules": ["composite", "polymer", "resin", "materials"],
        "exclude_rules": ["stock", "sports"],
        "must_include_any": ["composite", "polymer", "resin", "materials", "manufacturing"],
        "must_exclude_any": ["stock", "sports", "celebrity"],
        "soft_signals": ["composites", "aerospace", "automotive", "manufacturing"],
        "source_tier": "B",
        "rss_or_listing_url": "https://www.compositesworld.com/rss",
        "crawl_mode": "rss",
        "use_direct_source": True,
        "allow_images": True,
        "language": "en",
        "country": "US",
        "enabled": False,  # 403 Forbidden
    },
    {
        "name": "C&EN News",
        "domain": "cen.acs.org",
        "type": "rss",
        "priority": 80,
        "tags": ["industry", "en"],
        "include_rules": ["polymer", "chemistry", "materials", "plastics"],
        "exclude_rules": ["stock", "sports"],
        "must_include_any": ["polymer", "chemistry", "materials", "plastics", "recycling"],
        "must_exclude_any": ["stock", "sports", "celebrity"],
        "soft_signals": ["chemistry", "polymer", "materials science"],
        "source_tier": "B",
        "rss_or_listing_url": "https://cen.acs.org/feeds/rss/latest.xml",
        "crawl_mode": "rss",
        "use_direct_source": True,
        "allow_images": True,
        "language": "en",
        "country": "US",
        "enabled": False,  # 404 Not Found
    },
    # English — Academic Journals
    {
        "name": "Nature Materials (Journal)",
        "domain": "nature-nmat-journal.local",
        "type": "rss",
        "priority": 95,
        "tags": ["academic", "en"],
        "include_rules": ["materials", "polymer", "processing"],
        "exclude_rules": ["careers"],
        "must_include_any": ["materials", "polymer", "processing", "composite"],
        "must_exclude_any": ["careers", "sports", "finance"],
        "soft_signals": ["materials science", "polymer", "processing"],
        "source_tier": "A",
        "rss_or_listing_url": "http://feeds.nature.com/nmat/rss/current",
        "crawl_mode": "rss",
        "use_direct_source": True,
        "allow_images": True,
        "language": "en",
        "country": "US",
        "enabled": True,
    },
    {
        "name": "ACS Macro Letters",
        "domain": "pubs.acs.org",
        "type": "rss",
        "priority": 90,
        "tags": ["academic", "en"],
        "include_rules": ["polymer", "macromolecules", "materials"],
        "exclude_rules": ["careers"],
        "must_include_any": ["polymer", "macromolecules", "materials", "processing"],
        "must_exclude_any": ["careers", "sports", "finance"],
        "soft_signals": ["polymer science", "macromolecular", "synthesis"],
        "source_tier": "A",
        "rss_or_listing_url": "https://pubs.acs.org/action/showFeed?jc=amlccd&type=etoc&feed=rss",
        "crawl_mode": "rss",
        "use_direct_source": True,
        "allow_images": True,
        "language": "en",
        "country": "US",
        "enabled": True,
    },
    {
        "name": "Polymer (Journal)",
        "domain": "sciencedirect.com",
        "type": "rss",
        "priority": 90,
        "tags": ["academic", "en"],
        "include_rules": ["polymer", "macromolecules", "processing"],
        "exclude_rules": ["careers"],
        "must_include_any": ["polymer", "macromolecules", "processing", "composite"],
        "must_exclude_any": ["careers", "sports", "finance"],
        "soft_signals": ["polymer science", "characterization", "synthesis"],
        "source_tier": "A",
        "rss_or_listing_url": "https://rss.sciencedirect.com/publication/science/00323861",
        "crawl_mode": "rss",
        "use_direct_source": True,
        "allow_images": True,
        "language": "en",
        "country": "NL",
        "enabled": True,
    },
    {
        "name": "MIT Materials Science (RSS)",
        "domain": "mit-ms-rss.local",
        "type": "rss",
        "priority": 85,
        "tags": ["academic", "en"],
        "include_rules": ["materials", "polymer", "processing"],
        "exclude_rules": [],
        "must_include_any": ["materials", "polymer", "processing"],
        "must_exclude_any": ["sports", "finance", "housing"],
        "soft_signals": ["research", "laboratory", "manufacturing"],
        "source_tier": "A",
        "rss_or_listing_url": "https://news.mit.edu/rss/topic/materialsscienceandengineering",
        "crawl_mode": "rss",
        "use_direct_source": True,
        "allow_images": True,
        "language": "en",
        "country": "US",
        "enabled": True,
    },
    # English — Orgs & University Labs
    {
        "name": "American Chemistry Council",
        "domain": "americanchemistry.com",
        "type": "rss",
        "priority": 85,
        "tags": ["industry", "en"],
        "source_tier": "A",
        "rss_or_listing_url": "https://www.americanchemistry.com/rss",
        "crawl_mode": "rss",
        "use_direct_source": True,
        "language": "en",
        "enabled": False,  # 403 Restricted Content
    },
    {
        "name": "Plastics Europe",
        "domain": "plasticseurope.org",
        "type": "rss",
        "priority": 85,
        "tags": ["policy", "en"],
        "source_tier": "A",
        "rss_or_listing_url": "https://plasticseurope.org/feed/",
        "crawl_mode": "rss",
        "use_direct_source": True,
        "language": "en",
        "enabled": False,  # 403 Forbidden
    },
    {
        "name": "Stanford MSE News",
        "domain": "mse.stanford.edu",
        "type": "rss",
        "priority": 80,
        "tags": ["academic", "en"],
        "source_tier": "A",
        "rss_or_listing_url": "https://mse.stanford.edu/news/all/rss",
        "crawl_mode": "rss",
        "use_direct_source": True,
        "language": "en",
    },
    {
        "name": "Berkeley Lab News",
        "domain": "newscenter.lbl.gov",
        "type": "rss",
        "priority": 75,
        "tags": ["academic", "en"],
        "source_tier": "A",
        "rss_or_listing_url": "https://newscenter.lbl.gov/feed/",
        "crawl_mode": "rss",
        "use_direct_source": True,
        "language": "en",
    },
    {
        "name": "K Show News",
        "domain": "k-online.de",
        "type": "rss",
        "priority": 80,
        "tags": ["industry", "en"],
        "source_tier": "B",
        "rss_or_listing_url": "https://k-online.de/pm_rss_en",
        "crawl_mode": "rss",
        "use_direct_source": True,
        "language": "en",
    },
    # Chinese — Industry & Gov
    {
        "name": "CNPC 节能新能源",
        "domain": "news.cnpc.com.cn",
        "type": "rss",
        "priority": 80,
        "tags": ["industry", "zh"],
        "include_rules": ["节能", "新能源", "材料"],
        "exclude_rules": ["体育", "房产", "股票"],
        "must_include_any": ["节能", "新能源", "材料", "塑料"],
        "must_exclude_any": ["体育", "房产", "股票", "招聘"],
        "soft_signals": ["新能源", "节能", "材料"],
        "source_tier": "A",
        "rss_or_listing_url": "http://news.cnpc.com.cn/cnpcnews/jn/rss.xml",
        "crawl_mode": "rss",
        "use_direct_source": True,
        "allow_images": True,
        "language": "zh",
        "country": "CN",
        "enabled": True,
    },
    {
        "name": "国家统计局 RSS",
        "domain": "stats.gov.cn",
        "type": "rss",
        "priority": 85,
        "tags": ["policy", "zh"],
        "include_rules": ["材料", "制造", "工业"],
        "exclude_rules": ["体育", "房产", "股票"],
        "must_include_any": ["材料", "制造", "工业", "塑料"],
        "must_exclude_any": ["体育", "房产", "股票", "招聘"],
        "soft_signals": ["统计", "工业", "制造业"],
        "source_tier": "A",
        "rss_or_listing_url": "https://www.stats.gov.cn/sj/zxfb/rss",
        "crawl_mode": "rss",
        "use_direct_source": True,
        "allow_images": True,
        "language": "zh",
        "country": "CN",
        "enabled": False,  # 404 Not Found
    },
    # Chinese — Academic & Industry
    {
        "name": "北化大学报",
        "domain": "journal.buct.edu.cn",
        "type": "rss",
        "priority": 95,
        "tags": ["academic", "zh", "buct"],
        "source_tier": "A",
        "rss_or_listing_url": "https://journal.buct.edu.cn/CN/rss_zxly_1674-5906.xml",
        "crawl_mode": "rss",
        "use_direct_source": True,
        "language": "zh",
    },
    {
        "name": "中国石化新闻",
        "domain": "sinopec.com",
        "type": "rss",
        "priority": 90,
        "tags": ["industry", "zh"],
        "source_tier": "A",
        "rss_or_listing_url": "http://www.sinopec.com/media_centre/rss.xml",
        "crawl_mode": "rss",
        "use_direct_source": True,
        "language": "zh",
        "enabled": False,  # 404 Not Found
    },
    {
        "name": "艾邦高分子 (微信公众号)",
        "domain": "feeddd.org/aibang",
        "type": "rss",
        "priority": 85,
        "tags": ["industry", "zh", "wechat"],
        "source_tier": "B",
        "rss_or_listing_url": "https://feeddd.org/feeds/wechat/aibang",
        "crawl_mode": "rss",
        "use_direct_source": True,
        "language": "zh",
        "enabled": False,  # feeddd.org returning 0 entries
    },
    {
        "name": "废塑料新观察 (微信公众号)",
        "domain": "feeddd.org/scrap-plastic",
        "type": "rss",
        "priority": 80,
        "tags": ["policy", "zh", "wechat"],
        "source_tier": "B",
        "rss_or_listing_url": "https://feeddd.org/feeds/wechat/scrap-plastic",
        "crawl_mode": "rss",
        "use_direct_source": True,
        "language": "zh",
        "enabled": False,  # feeddd.org returning 0 entries
    },
    {
        "name": "塑料行业 (微信公众号)",
        "domain": "feeddd.org/plastic-industry",
        "type": "rss",
        "priority": 80,
        "tags": ["industry", "zh", "wechat"],
        "source_tier": "B",
        "rss_or_listing_url": "https://feeddd.org/feeds/wechat/plastic-industry",
        "crawl_mode": "rss",
        "use_direct_source": True,
        "language": "zh",
        "enabled": False,  # feeddd.org returning 0 entries
    },
    {
        "name": "Plastemart 塑料行业聚合",
        "domain": "plastemart.com",
        "type": "rss",
        "priority": 70,
        "tags": ["industry", "en"],
        "include_rules": ["polymer", "plastics", "resin"],
        "exclude_rules": ["stock", "sports"],
        "must_include_any": ["polymer", "plastics", "resin", "processing"],
        "must_exclude_any": ["stock", "sports", "celebrity"],
        "soft_signals": ["plastics", "industry", "polymer"],
        "source_tier": "B",
        "rss_or_listing_url": "https://www.plastemart.com/rss-feeds-plastics-industry",
        "crawl_mode": "rss",
        "use_direct_source": True,
        "allow_images": True,
        "language": "en",
        "country": "IN",
        "enabled": True,
    },
    {
        "name": "RecyclingInside",
        "domain": "recyclinginside.com",
        "type": "rss",
        "priority": 75,
        "tags": ["policy", "en"],
        "include_rules": ["recycling", "plastic", "polymer", "waste"],
        "exclude_rules": ["stock", "sports"],
        "must_include_any": ["recycling", "plastic", "polymer", "waste"],
        "must_exclude_any": ["stock", "sports", "celebrity"],
        "soft_signals": ["recycling", "circular economy", "waste management"],
        "source_tier": "B",
        "rss_or_listing_url": "https://recyclinginside.com/rss-feeds/",
        "crawl_mode": "rss",
        "use_direct_source": True,
        "allow_images": True,
        "language": "en",
        "country": "US",
        "enabled": True,
    },
    {
        "name": "金纬机械动态",
        "domain": "jwell.cn",
        "type": "industry",
        "priority": 73,
        "tags": ["company", "extrusion", "equipment"],
        "include_rules": ["挤出", "设备", "塑料", "回收"],
        "exclude_rules": ["体育", "房产", "股票"],
        "must_include_any": ["挤出", "设备", "塑料", "回收", "造粒", "中空成型"],
        "must_exclude_any": ["体育", "房产", "股票", "招聘"],
        "soft_signals": ["生产线", "交付", "工厂", "全球布局"],
        "source_tier": "company-newsroom",
        "rss_or_listing_url": None,
        "crawl_mode": "search",
        "use_direct_source": False,
        "allow_images": True,
        "language": "zh",
        "country": "CN",
        "enabled": True,
    },
    {
        "name": "Nature Materials",
        "domain": "nature.com",
        "type": "academic",
        "priority": 85,
        "tags": ["academic", "global"],
        "include_rules": ["materials", "polymer"],
        "exclude_rules": ["careers"],
        "must_include_any": ["polymer", "materials", "processing", "composite"],
        "must_exclude_any": ["career", "sports", "finance"],
        "soft_signals": ["mechanism", "processing", "manufacturing"],
        "source_tier": "academic-journal",
        "rss_or_listing_url": "http://feeds.nature.com/nmat/rss/current",
        "crawl_mode": "rss",
        "use_direct_source": True,
        "allow_images": True,
        "language": "en",
        "country": "US",
        "enabled": True,
    },
    {
        "name": "MIT News Materials",
        "domain": "news.mit.edu",
        "type": "academic",
        "priority": 70,
        "tags": ["academic", "materials"],
        "include_rules": ["materials", "polymer"],
        "exclude_rules": [],
        "must_include_any": ["materials", "polymer", "processing"],
        "must_exclude_any": ["sports", "finance", "housing"],
        "soft_signals": ["research", "laboratory", "manufacturing"],
        "source_tier": "academic-journal",
        "rss_or_listing_url": "https://news.mit.edu/rss/topic/materials-science",
        "crawl_mode": "rss",
        "use_direct_source": True,
        "allow_images": True,
        "language": "en",
        "country": "US",
        "enabled": True,
    },
]


DEFAULT_SETTINGS = {
    "report_settings": {
        "report_hour": 10,
        "report_minute": 0,
        "shadow_mode": True,
        "scrape_timeout_seconds": settings.scrape_timeout_seconds,
        "scrape_concurrency": settings.scrape_concurrency,
        "max_extractions_per_run": settings.max_extractions_per_run,
        "report_primary_model": settings.report_primary_model,
        "report_fallback_model": settings.report_fallback_model,
    }
}


def seed_defaults(session) -> None:
    existing_sources = {source.domain: source for source in session.scalars(select(Source)).all()}
    direct_source_disabled_domains = {"86pla.com", "newsroom.haitian.com"}
    for payload in DEFAULT_SOURCES:
        existing = existing_sources.get(payload["domain"])
        if existing is None:
            session.add(Source(**payload))
            continue
        for field, value in payload.items():
            current = getattr(existing, field)
            if field in {"must_include_any", "must_exclude_any", "soft_signals"} and not current:
                setattr(existing, field, value)
            elif field == "source_tier" and (not current or current == "unknown"):
                setattr(existing, field, value)
            elif field == "rss_or_listing_url" and not current and value:
                setattr(existing, field, value)
            elif field == "use_direct_source" and not current and value:
                setattr(existing, field, value)
            elif field == "crawl_mode" and current == "search" and value != "search":
                setattr(existing, field, value)
            elif field == "enabled" and current and not value:
                setattr(existing, field, value)
        if existing.domain in direct_source_disabled_domains:
            existing.use_direct_source = False

    for key, value in DEFAULT_SETTINGS.items():
        setting = session.get(AppSetting, key)
        if setting is None:
            session.add(AppSetting(key=key, value=value))
        else:
            merged = {**value, **setting.value}
            if key == "report_settings":
                merged = {field: merged.get(field, default) for field, default in value.items()}
            if key == "report_settings" and merged.get("report_fallback_model") == "minimax/minimax-m2.5:free":
                merged["report_fallback_model"] = settings.report_fallback_model
            if merged != setting.value:
                setting.value = merged

    admin_exists = session.scalars(select(User).where(User.is_admin.is_(True))).first()
    if admin_exists is None:
        session.add(
            User(
                email=settings.admin_email,
                password_hash=hash_password(settings.admin_password),
                is_admin=True,
                is_active=True,
            )
        )
